---
- name: Add a user with sudoer priviledge.
  hosts: localhost
  connection: local
  become: true
  vars:
    user: user

  tasks:
  - name: create an user
    user:
      name: "{{user}}"
      shell: /bin/bash
      groups: sudo
      append: true
      password: "{{ 'user' | password_hash('sha512') }}"

  - name: add the user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{user}}"
      content: "{{user}}    ALL=(ALL)  NOPASSWD: ALL"