---
- name: Create SSH key and deploy
  hosts: localhost
  connection: local

  tasks:
  - name: create .ssh
    become: false
    file: path="~/.ssh" state=directory

  - name: create SSH key
    openssh_keypair:
      path: "~/.ssh/id_rsa"

  