---
- name: install SDKMan
  hosts: localhost
  connection: local

  tasks:
  - name: Install SDKMan
    shell: "curl -s 'https://get.sdkman.io' | bash"
    args:
      executable: /bin/bash

  - name: Adding SDK Man to bash_profile
    lineinfile:
      path: ~/.bashrc
      line: "{{ item }}"
      state: present
      create: yes
    with_items:
      - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'