---
- name: Anaconda Installation
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - download_path: "$HOME/tmp/install-miniconda.sh"
    - installation_dir: "$HOME/miniconda3"

  tasks:
    - name: download Miniconda installer file
      get_url:
        url: "https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh"
        dest: "{{ download_path }}"
        mode: 0755

    - name: Run the installer
      shell: "{{ download_path }} -b -u"

    - name: .bashrc에 추가
      lineinfile:
        dest: ~/.bashrc
        regexp: 'etc/profile.d/conda.sh$'
        line: ". /home/kwlee/miniconda3/etc/profile.d/conda.sh"
        backup: yes

    - name: update conda
      command: conda update -y -q -n base -c defaults conda

    - name: Remove the installer
      file: state=absent path="{{ download_path }}"