---
- name: System Utilites Installation
  hosts: localhost
  connection: local
  become: true
  gather_facts: no

  tasks:
    - name: create .local/bin
      become: false
      file: path=~/.local/bin state=directory
    - name: create ~/.bash_aliases file if not exists
      become: false
      copy: dest=~/.bash_aliases content="" force=false

    - name: build-essential 설치
      apt: name=build-essential state=present
    - name: git 설치
      apt: name=git state=present
    - name: ripgrep 설치
      apt: name=ripgrep state=present
    - name: tldr 설치
      apt: name=tldr state=present
    - name: htop 설치
      apt: name=htop state=present
    - name: btop 설치
      snap: name=btop state=present
    - name: fzf 설치
      apt: name=fzf state=present
    - name: neofetch 설치
      apt: name=neofetch state=present
    - name: net-tools 설치
      apt: name=net-tools state=present
    - name: autojump 설치
      apt: name=autojump state=present
    - name: ffmpeg 설치
      apt: name=ffmpeg state=present
    - name: trash-cli 설치
      apt: name=trash-cli state=present

    - name: bat 설치
      apt: name=bat state=present
    - name: create alias
      become: false
      lineinfile:
        dest: ~/.bash_aliases
        regexp: 'alias bat=.*$'
        line: "alias bat='/usr/bin/batcat'"
        backup: yes

    # - name: zoxide 설치
    #   shell: "curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash"
    # - name: zoxide setup
    #   lineinfile:
    #     name: ~/.bashrc
    #     line: 'eval "$(zoxide init bash)"'

    - name: fd 설치
      apt: name=fd-find state=present
    - name: update find for fd
      become: false
      lineinfile:
        dest: ~/.bash_aliases
        regexp: 'alias fd=.*$'
        line: "alias fd='/bin/fdfind'"
        backup: yes

    - name: gdu 설치
      unarchive:
        src: https://github.com/dundee/gdu/releases/latest/download/gdu_linux_amd64.tgz
        dest: /usr/local/bin
        mode: 0755
        remote_src: true
    - name: create symbolic link from gdu_linux_amd64 to gdu
      file: src=/usr/local/bin/gdu_linux_amd64 dest=/usr/local/bin/gdu state=link

    - name: cpufetch 설치
      snap: name=cpufetch state=present