---
- name: Add a share
  hosts: all

  vars_prompt:
    - name: share_name
      prompt: "Share name"
    - name: client_id
      prompt: "Samba client user id"
    - name: share_path
      prompt: "Path to the share directory"

  tasks:
    - name: create an user
      blockinfile:
        path: /etc/samba/smb.conf
        append_newline: yes
        prepend_newline: yes
        block: |
          [{{ share_name }}]
          path = {{ share_path }}
          valid users = {{ client_id }}
          read only = no
          writable = yes
          guest ok = no
          browseable = yes
          create mask = 0755
          directory mask = 0755
      become: true