- name: Ensure required dependencies are installed
  become: true
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Check if SDKMAN is already installed
  stat:
    path: "{{ user_home_dir }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_installed

- name: Instance SDKMAN if not installed
  include_tasks: task_install_sdkman.yml
  when: not sdkman_installed.stat.exists

