- name: Ensure required dependencies are installed
  become: true
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Check if SDKMAN is already installed
  stat:
    path: "/home/{{ user_id }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_installed

- name: Miniconda3 설치
  include_tasks: task_install_sdkman.yml
  when: not sdkman_installed.stat.exists

