
- name: Install SDKMAN
  shell: |
    curl -s "https://get.sdkman.io" | bash
  args:
    executable: /bin/bash

- name: Refresh shell environment
  shell: |
    source {{ user_home_dir }}/.bashrc
  args:
    executable: /bin/bash
