
- name: Check if SDKMAN is already installed
  stat:
    path: "/home/{{ user_id }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_installed

- name: Install Gradle 8.9 using SDKMAN
  shell: |
    source /home/{{ user_id }}/.sdkman/bin/sdkman-init.sh && sdk install gradle {{ gradle_version }}
  args:
    executable: /bin/bash
  environment:
    SDKMAN_DIR: "/home/{{ user_id }}/.sdkman"
  when: sdkman_installed.stat.exists