---
# MongoDB 설치를 위한 tasks

- name: Import MongoDB public GPG key
  shell: curl -fsSL https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc | gpg --dearmor -o /usr/share/keyrings/mongodb.gpg
  args:
    creates: /usr/share/keyrings/mongodb.gpg
  become: true

- name: Add MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse
    state: present
    filename: mongodb-org-{{ mongodb_version }}
  become: true

- name: Install MongoDB packages
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  become: true
  notify: restart mongodb

- name: Ensure MongoDB service is enabled and started
  systemd:
    name: mongod
    state: started
    enabled: yes
  become: true 