
- name: install dependents tools
  become: true
  apt: 
    pkg:
      - software-properties-common
      - apt-transport-https
      - wget
    state: present

# - name: add MS GPG public key
#   become: true
#   shell: wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -

- name: add MS GPG public key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: register MS repository
  become: true
  shell:  add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  
- name: install VSCode 
  become: true
  apt: name=code state=latest update_cache=true