---
- hosts: localhost
  connection: local

  handlers:
  - name: restart xrdp
    service: name=xrdp state=restarted

  tasks:
  - name: install xrdp
    become: true
    package:
      name:
        - xserver-xorg-core
        - xserver-xorg-input-all
        - xrdp
      state: latest

  - name: add xrdp user
    become: true
    user: name=xrdp group=ssl-cert

  - name: xrdp 설정 변경 (접속시 검은 화면만 보이는 경우)
    become: true
    lineinfile:
      dest: /etc/xrdp/startwm.sh
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - regexp: "^unset DBUS_SESS"
        line: "unset DBUS_SESSION_BUS_ADDRESS"
      - regexp: "^unset XDG_RUNTIME"
        line: "unset XDG_RUNTIME_DIR"
    notify: restart xrdp

  - name: Login 과정에서 password 설정 후 멈추는 문제 해결 1/2
    become: true
    command: systemctl set-default graphical
  - name: Login 과정에서 password 설정 후 멈추는 문제 해결 2/2
    become: true
    command: systemctl isolate graphical

  - name: Password 지속적으로 물어보는 현상 해결 (1/2)
    become: true
    copy:
      dest: /etc/polkit-1/localauthority/50-local.d/color.pkla
      content: |
        [Allow colord for all users]
        Identity=unix-user:*
        Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
        ResultAny=yes
        ResultInactive=yes
        ResultActive=yes
      mode: 0755

  - name: Password 지속적으로 물어보는 현상 해결 (2/2)
    become: true
    copy:
      dest: /etc/polkit-1/localauthority/45-allow-colord.pkla
      content: |
        [Allow Colord all Users]
        Identity=unix-user:*
        Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
        ResultAny=no
        ResultInactive=no
        ResultActive=yes

        [Allow Package Management all Users]
        Identity=unix-user:*
        Action=org.debian.apt.*;io.snapcraft.*;org.freedesktop.packagekit.*;com.ubuntu.update-notifier.*
        ResultAny=no
        ResultInactive=no
        ResultActive=yes
      mode: 0755