
- name: install Vim
  become: true
  package: name=vim
  
- name: copy colorschema 
  copy: src="{{item}}" dest=~/.vim/colors/
  with_fileglob:
    - "files/*.vim"

- name: Vim 설정 파일 복사
  copy: src=files/vimrc dest=~/.vimrc