
- name: check whether SDKMan is installed or not
  become: false
  lineinfile:
    path: ~/.bashrc
    regexp: "^export SDKMAN_DIR="
    state: absent
  check_mode: yes
  register: sdk_present

- name: install SDKMan
  become: false
  shell: 'curl -s "https://get.sdkman.io" | bash'
  args:
    executable: /bin/bash
    creates: ~/.sdkman
  when: not sdk_present.found

  