---
- name: OS 인증서 폴더 생성
  become: true
  file: path=/etc/pki/ca-trust/source/anchors state=directory

- name: OS에서 인증서를 업데이트.
  become: true
  copy:
    src: "{{ ca_path }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ ca_path | basename }}"
    force: false
    remote_src: "{{ remote_src }}"
  register: ca_registered

- name: 인증서 업데이트
  become: true
  command: update-ca-certificates
  when: ca_registered