---
- name: Install TimescaleDB
  hosts: all

  vars:
    postgres_version: "17"

  tasks:
    - name: Install dependent packages
      apt:
        name:
          - gnupg
          - postgresql-common
          - apt-transport-https
          - lsb-release
          - wget
        update_cache: true
        state: present

    - name: Run the PostgreSQL package setup script
      shell: sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

    - name: Install
      package: name=postgresql-server-dev-{{postgres_version}} state=latest update_cache=true

    - name: Add the TimescaleDB repository
      apt_repository:
        repo: deb https://packagecloud.io/timescale/timescaledb/ubuntu/ {{ ansible_distribution_release }} main
        state: present
        filename: timescaledb.list
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the TimescaleDB GPG key
      shell: |
        wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg
    
    - name: Ensure apt is up to date
      apt: update_cache=yes

    - name: Install TimescaleDB
      package:
        name:
          - timescaledb-2-postgresql-{{postgres_version}}
          - postgresql-client-{{postgres_version}}
        state: present
        update_cache: yes

    - name: Tune your PostgreSQL instance for TimescaleDB
      shell: sudo timescaledb-tune --quiet --yes

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
        enabled: yes

    - name: Login to PostgreSQL
      shell: sudo -u postgres psql -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"
