---

- name: Add the GPG key
  become: true
  apt_key:
    url: "{{ chrome_apt_key_url }}"
    state: present

- name: Add repository into sources list
  become: true
  apt_repository:
    repo: "{{ chrome_repo }}"
    state: present
    filename: google-chrome
    
- name: Install google-chrome-stable
  become: true
  apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true