---
- name: install ROS2 package
  hosts: all

  vars:
    user_home_dir: "{{ ansible_env.HOME }}"
    ROS_DOMAIN_ID: "31"

  tasks:
    - name: Update fcitx configuration file to change the default input method
      lineinfile:
        path: "{{ user_home_dir }}/.config/fcitx/config"
        regexp: '^#TriggerKey='
        line: 'TriggerKey=SHIFT_SPACE HANGUL'
        state: present
      become: false