---
- name: install ROS2 package
  hosts: all

  vars:
    user_home_dir: "{{ ansible_env.HOME }}"
    ROS_DOMAIN_ID: "31"

  tasks:
    - name: Configure ROS2 settings
      block:
        - name: Remove the previous ROS2 configuration
          blockinfile:
            path: "{{ user_home_dir }}/.bashrc"
            marker: "# ROS2: {mark}"
            state: absent
        - name: Configure ROS2 in bashrc
          blockinfile:
            path: "{{ user_home_dir }}/.bashrc"
            prepend_newline: yes
            append_newline: yes
            marker: "# ROS2: {mark}"
            block: |
              source /opt/ros/humble/setup.bash
              source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

              alias cc='colcon'
              
              export RCUTILS_COLORIZED_OUTPUT=1
              export ROS2_DOMAIN_ID={{ ROS_DOMAIN_ID }}
              export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      become: false