---
- name: install ROS2 package
  hosts: all
  become: true

  tasks:
    - name: Ensure apt is up to date
      apt:
        update_cache: yes

    - name: Ensure that the Ubuntu Universe repository is enabled.
      apt:
        name:
          - software-properties-common
          - curl
          - gnupg2
          - lsb-release
        state: present

    - name: Enable Universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present

    - name: Add ROS 2 GPG key
      get_url:
        url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.key'
        dest: /usr/share/keyrings/ros-archive-keyring.gpg

    - name: Check ROS 2 APT repository file
      stat:
        path: /etc/apt/sources.list.d/ros2.list
      register: ros2_apt_repository

    - name: Add ROS 2 APT repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
      args:
        executable: /bin/bash
      when: ros2_apt_repository.stat.exists == False

    - name: Upgrade apt packages
      apt: upgrade=yes update_cache=yes

    - name: Install ROS 2 Humble packages
      apt:
        name:
          - ros-humble-desktop
          - ros-dev-tools
        state: present

    - name: Source ROS 2 setup in bashrc
      lineinfile:
        path: ~/.bashrc
        line: "source /opt/ros/humble/setup.bash"
        state: present

    - name: Install ROS 2 Python dependencies
      apt:
        name:
          - python3-colcon-common-extensions
          - python3-rosdep
          - python3-argcomplete
        state: present

    - name: Install turtlesim
      apt: name=ros-humble-turtlesim state=present update_cache=yes

    - name: Check turtlesim is installed
      shell: |
        source /opt/ros/humble/setup.bash
        ros2 pkg executables turtlesim
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Install rqt
      become: yes
      shell: apt install ~nros-foxy-rqt*

    - name: Initialize rosdep
      become: yes
      shell: |
        rosdep init
        rosdep update
      args:
        executable: /bin/bash
      ignore_errors: yes