---
- name: Install gui package
  hosts: all

  pre_tasks:
    - name: Install dconf-cli, dconf editor
      package:
        name:
          - gnome-tweaks
          - dconf-cli
          - dconf-editor
          - dbus-x11
        update_cache: true
        state: present
      become: true

    - name: Install psutil via apt (Ubuntu 22.04+)
      apt:
        name: python3-psutil
      become: true

  roles:
    - name: Adapt Ubuntu Desktop
      role: ubuntu_desktop
      when: ansible_virtualization_type != 'wsl'

    - name: Install gnome-terminal
      role: gnome-terminal

    - name: Install Tilix
      role: tilix

    - name: Install Hangul input
      role: hangul

    - name: Install google-chrome
      role: google-chrome
      when: ansible_virtualization_type != 'wsl'

    - name: Install xrdp
      role: xrdp