---
- name: install desktop package
  hosts: all

  vars:
    user_id: "{{ ansible_user_id }}"

    sdkman_java_version: "21.0.5-tem"
    sdkman_gradle_version: "8.9"

  roles:
    # - role: temurin_jdk

    - role: eclipse

    - role: uv

    - role: vscode
      when: "ansible_virtualization_type | default('') != 'wsl'"

    - role: docker

    - role: portainer
      vars:
        portainer_additional_ports:
          - "9000:9000"

    - role: sdkman
