---
- name: install ROS2 package
  hosts: all

  vars:
    user_home_dir: "{{ ansible_env.HOME }}"
    ROS_DOMAIN_ID: "31"

  tasks:
    - name: Install difftastic
      community.general.snap:
        name: difftastic
        state: present
      become: true