---
- name: install desktop package
  hosts: all

  vars:
    user_id: "{{ ansible_user_id }}"
    
  roles:
    - role: python3
    - role: tmux
    - role: vscode
      when: ansible_virtualization_type != 'wsl'
    - role: docker
    - role: sdkman
