---
tmp_dir: /tmp
jdk8_url: "https://drive.google.com/uc?id=1OnYq01NK8_z2R69BJE2I8Q8A9NVS4s_G"
jdk8_installer: "jdk-8u202-linux-x64.tar.gz"
jdk8_installer_path: "{{tmp_dir}}/{{jdk8_installer}}"
jdk8_home_dir: "/opt/jdk1.8.0_202"
