---
# Docker user to add to docker group (optional)
# docker_user: "{{ ansible_user }}"

# Docker Compose version for standalone installation
docker_compose_version: "v2.24.5"

# Whether to install Docker Compose standalone binary
# (Docker Compose plugin is installed by default with Docker CE)
docker_compose_standalone: false

# Docker service configuration
docker_service_enabled: true
docker_service_state: started 