---
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
deb_architecture: {
  "aarch64": "arm64",
  "x86_64": "amd64"
}
arch: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"
docker_repo: "deb [arch={{ arch }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

user_id: "{{ ansible_user_id }}"
user_home_dir: "{{ ansible_env.HOME }}"
