---
- name: "common: 주요 모듈 설치"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    common_dir: ~/development/common
    github_base: https://github.com/kwlee0220
    modules:
      - utils
      - utilsx
      - utils.geo
      - utils.grpc
    proto_modules:
      - utils.grpc

  pre_tasks:
  - name: create base directory
    file: path={{ common_dir }} state=directory

  tasks:
  - name: git clone modules
    git:
      repo: "{{ github_base }}/{{ item }}.git"
      dest: "{{ common_dir }}/{{ item }}"
      clone: yes
    with_items: "{{ modules }}"

  - name: generate protos
    command: gradle -q generateProto
    args:
      chdir: "{{ common_dir }}/{{ item }}"
    with_items: "{{ proto_modules }}"

  - name: create Eclipse project settings
    command: gradle -q eclipse
    args:
      chdir: "{{ common_dir }}/{{ item }}"
    with_items: "{{ modules }}"