---
- name: "common: 주요 모듈 설치"
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - module_vars.yml
  vars:
    base_dir: ~/development/common

  pre_tasks:
  - name: create base directory
    file: path={{ base_dir }} state=directory

  tasks:
  - name: git clone modules
    git:
      repo: "{{ github_base }}/{{ item }}.git"
      dest: "{{ base_dir }}/{{ item }}"
      clone: yes
    with_items: "{{ modules.commons }}"

  - name: generate protos
    command: gradle -q generateProto
    args:
      chdir: "{{ base_dir }}/{{ item }}"
    with_items: "{{ protos.commons }}"

  - name: create Eclipse project settings
    command: gradle -q eclipse
    args:
      chdir: "{{ base_dir }}/{{ item }}"
    with_items: "{{ modules.commons }}"