---
- name: install dependents tools
  become: true
  package: 
    name:
      - software-properties-common
      - apt-transport-https
      - wget

- name: add MS GPG public key
  become: true
  apt_key:
    url: "{{ vscode_gpg_url }}"
    state: present

- name: register MS repository
  become: true
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
  
- name: install VSCode 
  become: true
  apt: name=code state=latest update_cache=true