---
- name: Install required packages
  package:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
    state: present
    update_cache: yes

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Microsoft GPG key
  get_url:
    url: "{{ vscode_gpg_url }}"
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'

- name: Add Microsoft repository
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
    filename: vscode
    update_cache: yes

- name: Install Visual Studio Code
  package:
    name: code
    state: latest
    update_cache: yes 