---
- name: update apt
  become: true
  apt: update_cache=yes

- name: copy .bashrc
  include_tasks: tasks/task_bashrc.yml

- name: install some terminal applications
  include_tasks: tasks/task_tools.yml

- name: generate SSH key
  include_role: name=generate_ssh_key