
- name: 주요 모듈들 설치
  package:
    name:
      - dos2unix
      - tree
      - zip
      - unzip
      - build-essential
      - ripgrep
      - tldr
      - htop
      - btop
      - neofetch
      - cpufetch
      - net-tools
      - ffmpeg
      - trash-cli
      - bat
      - fd-find
    state: latest
  become: true

- name: Install autojump & configure autojump
  block:
    - name: Install autojump
      package: name=autojump state=latest
      become: true

    - name: Configure autojump
      lineinfile:
          path: ~/.bashrc
          regexp: 'source /usr/share/autojump/autojump.sh'
          line: "[[ -s /usr/share/autojump/autojump.sh ]] && source /usr/share/autojump/autojump.sh"
          state: present

- name: gdu 설치 과정
  become: true
  block:
    - name: Download gdu binary
      get_url:
        url: "https://github.com/dundee/gdu/releases/latest/download/gdu_linux_amd64.tgz"
        dest: "/tmp/gdu_linux_amd64.tgz"

    - name: Extract gdu binary
      unarchive:
        src: "/tmp/gdu_linux_amd64.tgz"
        dest: "/usr/local/bin/"
        remote_src: yes
  ignore_errors: true
