
- name: 주요 모듈들 설치
  package:
    name:
      - dos2unix
      - tree
      - zip
      - unzip
      - build-essential
      - ripgrep
      - tldr
      # - htop
      - btop
      - neofetch
      - cpufetch
      - net-tools
      - ffmpeg
      # - trash-cli
      - bat
      - fd-find
      - jq
    state: latest
  become: true

- name: Install autojump & configure autojump
  block:
    - name: Install autojump
      package: name=autojump state=latest
      become: true
    - name: Configure autojump
      lineinfile:
          path: "{{ user_home_dir }}/.bashrc"
          regexp: 'source /usr/share/autojump/autojump.sh'
          line: "[[ -s /usr/share/autojump/autojump.sh ]] && source /usr/share/autojump/autojump.sh"
          state: present
    - command: "dos2unix {{ user_home_dir }}/.bashrc"

- name: Install gdu application
  block:
    - name: Download gdu binary
      get_url:
        url: "https://github.com/dundee/gdu/releases/latest/download/gdu_linux_amd64.tgz"
        dest: "/tmp/gdu_linux_amd64.tgz"
    - name: Extract gdu binary
      unarchive:
        src: "/tmp/gdu_linux_amd64.tgz"
        dest: "/usr/local/bin/"
        remote_src: yes
  ignore_errors: true
  become: true

- name: Install fzf application
  include_role: name=fzf

# - name: install Atuin
#   include_role: name=atuin

- name: Install vim
  include_role: name=vim

- name: Install jless
  block:
    - name: Add jless repository
      shell: echo '\n' | add-apt-repository ppa:gslin/jless
    - name: Install jless
      apt: name=jless state=latest update_cache=yes
  become: true

- name: Install difftastic
  community.general.snap:
    name: difftastic
    state: present
  become: true