---
  - name: Upgrade apt packages
    hosts: all
    become: true

    tasks:
    - name: upgrade apt packages
      apt: upgrade=yes update_cache=yes

    - name: Reboot the target computer to apply the upgrade
      reboot:
        msg: "Rebooting the target computer to apply the upgrade"
        reboot_timeout: 300
      become: true