---
# Node.js 설치를 위한 tasks

- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: true

- name: Add NodeSource repository key
  shell: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
  args:
    creates: /usr/share/keyrings/nodesource.gpg
  become: true

- name: Add NodeSource repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main
    state: present
    filename: nodesource
  become: true

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ nodejs_install_global_packages }}"
  become: true
  when: nodejs_install_global_packages | length > 0 