---

- name: create a service file for Zookeeper with copy module
  become: true
  copy:
    dest: /etc/systemd/system/zookeeper.service
    content: |
      [Unit]
      Requires=network.target remote-fs.target
      After=network.target remote-fs.target
      [Service]
      Type=simple
      User=kafka
      ExecStart={{ kafka_home_dir }}/bin/zookeeper-server-start.sh {{ kafka_home_dir }}/config/zookeeper.properties
      ExecStop={{ kafka_home_dir }}/bin/zookeeper-server-stop.sh
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
    mode: 0755

- name: create a service file for Kafka with copy module
  become: true
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Requires=zookeeper.service
      After=zookeeper.service
      [Service]
      Type=simple
      User=kafka
      ExecStart=/bin/sh -c '{{ kafka_home_dir }}/bin/kafka-server-start.sh {{ kafka_home_dir }}/config/server.properties'
      ExecStop={{ kafka_home_dir }}/bin/kafka-server-stop.sh
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
    mode: 0755