---
dependencies: []
galaxy_info:
  author: kwlee
  description: Install ROS2 Humble and configure environment
  company: ''
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - ros2
    - robotics
    - humble
    - desktop 