---
dependencies: []
galaxy_info:
  author: kwlee
  description: Install ROS 2 (Humble / Jazzy) and configure environment
  company: ''
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - ros2
    - robotics
    - humble
    - jazzy
    - desktop
