---
galaxy_info:
  author: Ansible User
  description: Install Eclipse Temurin JDK
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - java
    - jdk
    - temurin
    - development

dependencies: [] 