---
- name: Add 'innercase' models
  hosts: all
  become: false

  vars_files:
    - vars/mdt_vars.yml

  vars:
    model_dir: "{{ mdt_home_dir }}/models/innercase"

  tasks:
    - name: Create directory for 'innercase' model
      file:
        path: "{{ model_dir }}"
        state: directory
        mode: '0755'

    - name: Copy 'innercase' model
      unarchive:
        src: "files/innercase.zip"
        dest: "{{ model_dir }}"
        remote_src: no
        mode: '0755'

    - name: Install necessary Python modules for 'innercase' instance
      pip:
        requirements: "{{ model_dir }}/requirements.txt"

    - name: Create inspector directory
      file:
        path: "{{ user_home_dir }}/tmp/inspector"
        state: directory
        mode: '0755'