---
- name: Add MDT pre-defined models
  hosts: all
  become: false

  vars:
    user_home_dir: "{{ ansible_env.HOME }}"
    model_dir: "{{ user_home_dir }}/mdt/models"

  tasks:
    - name: Create MDT directory models
      file:
        path: "{{ model_dir }}"
        state: directory
        mode: '0755'

    - name: MDT 모델 등록 스크립트 복사
      copy:
        src: "files/add_models.sh"
        dest: "{{ model_dir }}/add_models.sh"
        mode: '0755'

- name: Import test model
  import_playbook: "models/model_test.yml"

- name: Import welder model
  import_playbook: "models/model_welder.yml"
- name: Import panda model
  import_playbook: "models/model_panda.yml"
