---
- name: Add MDT pre-defined models
  hosts: all
  become: false

  vars_files:
    - vars/mdt_vars.yml

  vars:
    model_home_dir: "{{ mdt_home_dir }}/models"

  tasks:
    - name: Create MDT directory models
      file:
        path: "{{ model_home_dir }}"
        state: directory
        mode: '0755'

    - name: MDT 모델 등록 스크립트 복사
      copy:
        src: "files/add_models.sh"
        dest: "{{ model_home_dir }}/add_models.sh"
        mode: '0755'

  roles:
    - role: postgresql_db
      vars:
        postgres_db: mdt_app
        postgres_user: "mdt"

- import_playbook: "model_test.yml"
- import_playbook: "model_welder.yml"
- import_playbook: "model_panda.yml"
