---
- name: Build MDT projects with Gradle
  hosts: all
  become: false

  vars_files:
    - mdt_vars.yml

  vars:
    common_dir: "{{ src_root_dir }}/common"
    mdt_dir: "{{ src_root_dir }}/mdt"
    mdtpy_dir: "{{ src_root_dir }}/mdtpy"

    utils_project_dir: "{{ common_dir }}/utils"
    pyutils_project_dir: "{{ common_dir }}/pyutils"
    mdt_client_project_dir: "{{ mdt_dir }}/mdt-client"
    faaast_lib_project_dir: "{{ mdt_dir }}/faaast/faaast-lib"
    faaast_starter_project_dir: "{{ mdt_dir }}/faaast/faaast-starter"
    mdt_instance_project_dir: "{{ mdt_dir }}/mdt-instance"
    mdt_manager_project_dir: "{{ mdt_dir }}/mdt-manager"
    mdt_operation_http_project_dir: "{{ mdt_dir }}/mdt-operation-http"
    mdt_workflow_argo_project_dir: "{{ mdt_dir }}/mdt-workflow-argo"

  tasks:
    - name: Build MDT projects with Gradle
      shell: |
        cd {{ item.dir }}
        gradle assemble
      args:
        executable: /bin/bash
      loop:
        # - { dir: "{{ utils_project_dir }}" }
        # - { dir: "{{ mdt_client_project_dir }}" }
        # - { dir: "{{ faaast_lib_project_dir }}" }
        # - { dir: "{{ faaast_starter_project_dir }}" }
        - { dir: "{{ mdt_instance_project_dir }}" }
        - { dir: "{{ mdt_manager_project_dir }}" }
        - { dir: "{{ mdt_operation_http_project_dir }}" }
        - { dir: "{{ mdt_workflow_argo_project_dir }}" }

    - name: Install necessary Python modules for 'mdtpy'
      pip:
        name:
          - dataclasses_json
        state: present
