---
- name: install MDT platform
  hosts: all

- name: MDTPlatform을 위한 기반 software를 설치
  import_playbook: "install_mdt_core_infra.yml"

- name: MDT platform 기반 구조 설치
  import_playbook: "deploy_mdt_platform.yml"
  
- name: MDT platform 소스 설치 및 빌드
  import_playbook: "build_mdt_platform.yml"

- name: 테스트용 MDT 모델 설치
  import_playbook: "add_builtin_instances.yml"
