---
- name: install necessary softwares for MDT platform
  hosts: all
  vars_files:
    - vars/mdt_vars.yml

  roles:
    - name: Install ROS2
      role: ros2
      when: install_ros2 | default(false) | bool

    # - name: Build ROS 2 MoveIt from Github
    #   role: ros_moveit_build
    #   when: install_ros2 | default(false) | bool
      
    # - name: Install ROS 2 Panda
    #   role: ros_panda
    #   when: install_ros2 | default(false) | bool
