---
- name: install MDT platform
  hosts: all

  vars_files:
    - vars/mdt_vars.yml

- name: MDTPlatform을 위한 기반 software를 설치
  import_playbook: "install_mdt_infra.yml"

- name: Build MDT projects with Gradle
  import_playbook: "build_mdt_projects.yml"

- name: MDT workspace 생성
  import_playbook: create_workspace.yml

- name: MDT platform GUI 설치
  import_playbook: "install_mdt_gui.yml"

- name: 테스트용 MDT 모델 설치
  import_playbook: "add_sample_models.yml"
