---
- name: install MDT platform
  hosts: all

# - name: MDTPlatform을 위한 기반 software를 설치
#   import_playbook: "install_mdt core_infra.yml"

- name: MDT platform 기반 구조 설치
  import_playbook: "deploy_mdt_platform.yml"
- name: MDT platform 소스 설치 및 빌드
  import_playbook: "build_mdt_platform.yml"