---
- name: Install necessary systems for MDT platform
  hosts: all

  vars:
    user_id: "{{ ansible_user_id }}"
    postgres_user: mdt
    postgres_db: mdt
    postgres_password: mdt2025

  roles:
    - role: basic_apps
    - role: docker
    - role: sdkman

- import_playbook: playbooks/postgresql/install_postgresql.yml
- import_playbook: playbooks/postgresql/install_pgadmin4.yml
- import_playbook: playbooks/postgresql/add_user_db.yml
- import_playbook: playbooks/mosquitto/install_mosquitto.yml