---
- name: install necessary softwares for MDT platform
  hosts: all

  vars:
    user_id: "{{ ansible_user_id }}"
    postgres_user: mdt
    postgres_db: mdt
    postgres_password: mdt2025

  roles:
    - role: basic_apps

  tasks:
    - name: python3-pip 설치
      package:
        name: python3-pip
        state: present
      become: true

- import_playbook: "../install_gradle.yml"
- import_playbook: "../install_temurin_jdk.yml"

- import_playbook: "../postgresql/install_postgresql.yml"
- import_playbook: "../postgresql/install_pgadmin4.yml"
- import_playbook: "../postgresql/add_user_db.yml"
  vars:
    postgres_db: mdt
    postgres_user: mdt
    postgres_password: mdt2025
- import_playbook: "../postgresql/add_db.yml"
  vars:
    postgres_db: mdt_app
    postgres_user: mdt
- import_playbook: "../postgresql/add_db.yml"
  vars:
    postgres_db: ksx9101
    postgres_user: mdt

- import_playbook: "../mosquitto/install_mosquitto.yml"