---
- name: install necessary softwares for MDT platform
  hosts: all
  vars_files:
    - vars/mdt_vars.yml

  roles:
    - role: basic_apps
    - role: temurin_jdk
    - role: gradle

    - name: Install PostgreSQL
      role: postgresql
      vars:
        postgres_version: 16

    - name: Create PostgreSQL user for MDTPlatform internal data
      role: postgresql_user
      vars:
        postgres_user: "{{ mdt_postgres_user }}"
        postgres_password: "{{ mdt_postgres_password }}"
    - name: Create PostgreSQL database for MDTPlatform internal data
      role: postgresql_db
      vars:
        postgres_db: "{{ mdt_postgres_db }}"
        postgres_user: "{{ mdt_postgres_user }}"
        postgres_password: "{{ mdt_postgres_password }}"

    - name: PgAdmin4
      role: pgadmin4

    - name: Install Mosquitto
      role: mosquitto

    - name: Install ROS2
      role: ros2
      when: install_ros2 | default(false)

    - name: Install docker
      role: docker
      when: install_minikube | default(true) or install_docker | default(true)

    - name: Install NodeRED
      role: nodered
      when: install_nodered | default(false)

  tasks:
    - name: python3-pip 설치
      package:
        name: python3-pip
        state: present
      become: true

- import_playbook: "../postgresql/install_pgadmin4.yml"

