---
- name: Install MDTPlatform Management and Workflow Management GUI
  hosts: all
  become: false

  vars_files:
    - mdt_vars.yml

  vars:
    mdt_gui_home: "{{ mdt_home_dir }}/mdt-gui"
    dtbackend_dir: "{{ mdt_gui_home }}/dtbackend-main"
    dtfront_dir: "{{ mdt_gui_home }}/dtfront-main"
    mdt_gui_zip_file: "files/mdt-gui.zip"

  roles:
    - role: nodejs
      vars:
        nodejs_install_global_packages:
          - yarn

  tasks:
    - name: Create top-level MDT GUI directory
      file:
        path: "{{ mdt_gui_home }}"
        state: directory
        mode: '0755'

    - name: Unzip MDT GUI
      unarchive:
        src: "{{ mdt_gui_zip_file }}"
        dest: "{{ mdt_gui_home}}"

    - name: Initialize MDT GUI
      shell: |
        cd {{ item }}
        yarn install
      args:
        executable: /bin/bash
      loop:
        - "{{ dtbackend_dir }}"
        - "{{ dtfront_dir }}"

    - name: Create environment file
      template:
        src: files/_env.development.j2
        dest: "{{ dtfront_dir }}/.env.development"

    - name: Start MDT GUI
      shell: |
        cd {{ item }}
        nohup yarn start > /dev/null 2>&1 &
        sleep 10
      args:
        executable: /bin/bash
      loop:
        - "{{ dtbackend_dir }}"
        - "{{ dtfront_dir }}"