---
- name: Create an user with sudo privilege
  hosts: all
  become: true

  vars_prompt:
    - name: user_id
      prompt: "User id"
      private: no
    - name: password
      prompt: "Password"

  tasks:
    - name: create an user
      user:
        name: "{{ user_id }}"
        shell: /bin/bash
        groups: sudo
        append: true
        password: "{{ password  | password_hash('sha512') }}"