---
- name: Install ibus-hangul and required packages
  apt:
    name:
      - ibus
      - ibus-hangul
      - language-pack-ko
      - fonts-nanum
    state: present
  become: true

- name: Start ibus daemon
  shell: |
    ibus-daemon -drx
  args:
    executable: /bin/bash

- name: Set Korean locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=ko_KR.UTF-8'
    state: present
  become: true

- name: Set ibus as the default input method
  shell: |
    im-config -n ibus
  args:
    executable: /bin/bash

- name: Add Korean input source for ibus
  shell: |
    gsettings set org.gnome.desktop.input-sources sources "[('ibus', 'hangul')]"
  args:
    executable: /bin/bash

- name: Set fonts to Nanum
  shell: |
    gsettings set org.gnome.desktop.interface font-name "Nanum Gothic 11"
    gsettings set org.gnome.desktop.interface document-font-name "Nanum Gothic 11"
    gsettings set org.gnome.desktop.wm.preferences titlebar-font "Nanum Gothic Bold 11"
  args:
    executable: /bin/bash