---

- name: Install Korean language pack and fonts
  package:
    name:
      - language-pack-ko
      - fonts-nanum
      - fonts-noto-cjk
    state: present
  become: true
  
- name: Install locales and configure UTF-8
  block:
  - name: install locale
    become: true
    apt: name=locales state=present

  - name: set UTF-8 locale
    become: true
    shell: |
      locale-gen ko_KR ko_KR.UTF-8
      update-locale LC_ALL=ko_KR.UTF-8 LANG=ko_KR.UTF-8

  - name: insert 'LANG=ko_KR.UTF-8' to .bashrc
    lineinfile:
      path: "{{ user_home_dir }}/.bashrc"
      line: "export LANG=ko_KR.UTF-8"
      insertafter: '# Copied from Ansible'
      
- name: Install Hangul for Ubuntu
  include_tasks: "ubuntu.yml"
  when: ansible_virtualization_type != 'wsl'

- name: Install Hangul for WSL2
  include_tasks: "wsl2.yml"
  when: ansible_virtualization_type == 'wsl'