---
- name: "Install ROS 2 {{ ros2_distro }} Panda dependencies"
  ansible.builtin.apt:
    name: "{{ ros_panda_packages | map('regex_replace', '^', ros2_pkg_prefix) | list }}"
    state: present
  become: true
