
- name: Create directory for the component
  file:
    path: "{{ component_dir }}"
    state: directory
    mode: '0755'

- name: Unarchive the component
  unarchive:
    src: "files/{{ component_name }}.zip"
    dest: "{{ component_dir }}"
    remote_src: no
    mode: '0755'