---
- name: Assign sudoer priviledge
  hosts: all
  become: true

  tasks:
  - name: add the user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{user}}"
      content: "{{user}}    ALL=(ALL)  NOPASSWD: ALL"