---
- name: Generate SSH key and deploy
  hosts: all
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - name: 접속 대상 노드들의 public key를 수집한다.
    command: /usr/bin/ssh-keyscan -t rsa {{ ansible_host }}
    register: keyscan

  - name: 수집된 public key를 know_hosts 파일에 추가한다.
    lineinfile:
      name: ~/.ssh/known_hosts
      create: yes
      line: "{{item}}"
    with_items:
      - "{{ keyscan.stdout_lines }}"