---
- name: Initialize Kubernetes control plane
  hosts: k8s_master
  become: true

  vars:
    endpoint:
      containerd: unix:///run/containerd/containerd.sock
      CRI-O: unix:///run/containerd/containerd.sock
      docker-engine: unix:///run/containerd/containerd.sock

  tasks:
    - name: Check if the control-plane node is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: initialize control-plane node
      command: >
        kubeadm init --pod-network-cidr=10.244.0.0/16 
        --apiserver-advertise-address={{ ansible_host }} 
        --cri-socket={{ endpoint.containerd }}
      when: kubeadm_init.stat.exists == false

    - name: create k8sadmin user and create a cluster
      block:
      - name: create home directory for root account
        user:
          name: root
          shell: /bin/bash
          create_home: true

      - name: Create .kube directory
        file: path=~/.kube state=directory mode=0755

      - name: Copy the kube config file
        copy:
          src: /etc/kubernetes/admin.conf
          dest: ~/.kube/config
          mode: 0644
          remote_src: yes

      - name: install bash-completion
        apt: name=bash-completion

      - name: copy Kubernetes Autocomplete configuration file
        copy:
          src: files/k8s_autocomplete_rc
          dest: "~/.k8s_autocomplete_rc"

      - name: update .bashrc to call .k8s_autocomplete_rc
        lineinfile:
          dest: "~/.bashrc"
          regexp: '^\. ~/.k8s_autocomplete_rc'
          line: ". ~/.k8s_autocomplete_rc"
          state: present
      
    - name: install the Flannel Pod network add-on
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Display registered output
      debug:
        var: kubernetes_join_command.stdout_lines

    - name: Create dummy host to store variable for node config
      add_host:
        name: "DUMMY_HOST"
        JOIN_COMMAND: "{{ kubernetes_join_command.stdout_lines[0] }}"


- name: Kubernetes Worker Initialization
  hosts: k8s_workers
  become: true
  tasks:
    - name: Check if the worker node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubeadm_join
    - name: Join the worker nodes to the cluster
      command: "{{ hostvars['DUMMY_HOST']['JOIN_COMMAND'] }}"
      when: kubeadm_join.stat.exists == false