---
- name: Docker's containerd Installation
  hosts: k8s
  become: true

  roles:
    - role: docker-engine

  tasks:
    - name: create containerd's default config file
      shell: containerd config default > /etc/containerd/config.toml
      
    - name: set 'SystemdCgroup' true
      replace:
        dest: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: "SystemdCgroup = true"
      notify: restart containerd

  handlers:
    - name: restart containerd
      service: name=containerd state=restarted enabled=true