---
- name: Install required Python3 packages
  become: true
  package:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
      - python3-venv
      - python3-setuptools
    state: latest
    update_cache: true

- name: upgrade pip
  command: python3 -m pip install pip --upgrade