---
kafka_version: 3.6.1
scala_version: 2.13

kafka_dir_name: kafka_{{ scala_version }}-{{ kafka_version }}
kafka_installer_url: https://downloads.apache.org/kafka/{{ kafka_version }}/{{ kafka_dir_name }}.tgz

installation_dir: /opt
kafka_home_dir: "{{ installation_dir }}/kafka"
heap_size: "1G"

hosts_in_group: "{{ groups[group_names[0]]}}"
id_seq: "{{ hosts_in_group.index(inventory_hostname) + 1 }}"
zookeepers: "{{ hosts_in_group | join(':2181,') }}:2181"