confluent_installation_dir: /opt
confluent_home_dir: "{{confluent_installation_dir}}/confluent"
confluent_tarball: "https://packages.confluent.io/archive/7.2/confluent-community-7.2.5.tar.gz"
confluent_user: confluent
confluent_group: confluent

confluent_data_dir: /var/confluent
zookeeper_data_dir: "{{confluent_data_dir}}/zookeeper"
kafka_log_dir: "{{confluent_data_dir}}/kafka/kafka-logs"