---
- name: start Minikube package
  hosts: all

  tasks:
    - name: Start Minikube with Docker driver
      shell: minikube start --memory=no-limit --cpus=no-limit
      args:
        executable: /bin/bash
      register: minikube_output
      changed_when: "'Already running' not in minikube_output.stdout"
    - debug:
        msg: "Minikube output: {{ minikube_output.stdout }}"