---
- name: Generate SSH key and deploy
  hosts: all

  tasks:
  - name: deploy SSH key
    authorized_key:
      user: "{{ansible_user_id}}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present

  