---
- name: Upgrade apt packages
  hosts: all
  become: true
  vars:
    user: test

  tasks:
  - name: create an user
    user:
      name: {{user}}
      shell: /bin/bash
      groups: sudo
      append: true
      password: "{{ 'password' | password_hash('sha512') }}"

  - name: add the user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{user}}"
      content: "{{user}}    ALL=(ALL)  NOPASSWD: ALL"
  - name: deploy SSH key
    authorized_key:
      user: {{user}}
      key: "{{ lookup('file', '/home/{{user}}/.ssh/id.pub') }}"
      state: present