---
- name: Join worker nodes to the control plane
  hosts: k8s_master
  become: true
  tasks:
    - name: Create a token for new worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Display registered output
      debug: var=kubernetes_join_command.stdout_lines

    - name: Create dummy host to store variable for node config
      add_host:
        name: "DUMMY_HOST"
        JOIN_COMMAND: "{{ kubernetes_join_command.stdout_lines[0] }}"

- name: Kubernetes Worker Initialization
  hosts: k8s_workers
  become: true
  tasks:
    - name: Check if the worker node is already joined
      stat: path=/etc/kubernetes/kubelet.conf
      register: kubeadm_join
    - debug: "var=hostvars['DUMMY_HOST']['JOIN_COMMAND']"
    - name: Join the worker nodes to the cluster
      command: "{{ hostvars['DUMMY_HOST']['JOIN_COMMAND'] }}"
      when: kubeadm_join.stat.exists == false