---
- name: Add a samba client
  hosts: all

  vars_prompt:
    - name: samba_client
      prompt: "Samba client user id"
      private: no
    - name: samba_client_passwd
      prompt: "Samba client password"

  tasks:
    - name: Install samba
      package: name=samba state=present
      become: true

    - name: create a samba user
      command: "smbpasswd -a {{ samba_client }}"
      args:
        stdin: "{{ samba_client_passwd }}\n{{ samba_client_passwd }}"
      register: smbpasswd_output
      ignore_errors: true
      notify: restart samba
      become: true

  handlers:
    - name: restart samba
      service: name=smbd state=restarted
      become: true