---
- name: Add a share
  hosts: all

  vars:
    share_name: home
    share_path: "/home/{{ ansible_user_id }}"
    samba_client: "{{ ansible_user_id }}"

  tasks:
    - name: Install samba
      package: name=samba state=present
      become: true

    - name: add a share
      blockinfile:
        path: /etc/samba/smb.conf
        append_newline: yes
        prepend_newline: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ share_name }}"
        block: |
          [{{ share_name }}]
          path = {{ share_path }}
          valid users = {{ samba_client }}
          read only = no
          writable = yes
          guest ok = no
          browseable = yes
          create mask = 0755
          directory mask = 0755
      become: true
      notify: restart samba

  handlers:
    - name: restart samba
      service: name=smbd state=restarted
      become: true