
- name: provide 'server.properties'
  become: yes
  become_user: "{{ confluent_user }}"
  template:
    src: server.properties.j2
    dest: "{{ confluent_home_dir }}/etc/kafka/server.properties"
    force: true
  vars:
    zookeeper_connect: "{{ ansible_play_hosts | map('regex_replace', '$', ':2181') | join(',') }}"
  tags: kafka

- name: prepare kafka's log directory
  become: yes
  file:
    path: "{{ kafka_log_dir }}"
    state: directory
    owner: "{{ confluent_user }}"
    group: "{{ confluent_group }}"
    mode: 0755
  tags: kafka