---
galaxy_info:
  author: Ansible User
  description: Install and configure PostgreSQL with PostGIS
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - postgresql
    - postgres
    - database
    - postgis

dependencies: [] 