---
- name: Assign sudoer priviledge
  hosts: all
  become: true

  vars_prompt:
    - name: user_id
      prompt: "User id"
      private: no

  tasks:
  - name: add the user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{ user_id }}"
      content: "{{ user_id }}    ALL=(ALL)  NOPASSWD: ALL"