---
- name: Docker Installation
  hosts: all
  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }
    arch: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"
    docker_repo: "deb [arch={{ arch }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    user_id: "{{ ansible_user_id }}"

  tasks:
    - debug: var=user_id

    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - lsb-release
          # - python3-pip
          # - virtualenv
          # - python3-setuptools
        state: latest
        update_cache: true

    - name: add Docker GPG apt key
      become: true
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: add Docker Repository
      become: true
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present

    - name: update apt and install docker-ce
      become: true
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: install docker-compose
      become: true
      apt:
        name: docker-compose-plugin
        state: latest
        update_cache: true

    - name: add user to docker
      become: true
      user: name="{{ user_id }}" groups=docker append=true