---
- name: Oracle JDK8 Installation
  hosts: all
  become: true
  vars:
    - jdk8_url: "https://drive.google.com/uc?id=1OnYq01NK8_z2R69BJE2I8Q8A9NVS4s_G"
    - jdk8_installer: "jdk-8u391-linux-x64.tar.gz"
    - jdk8_installer_path: "{{ tmp_dir }}/{{ jdk8_installer }}"

  tasks:
    - name: download JDK installer file from Google Cloud.
      become: true
      shell: "~/miniconda3/bin/gdown -q {{ jdk8_url }} -O {{  jdk8_installer_path }}"
      args:
        creates: " {{ jdk8_installer_path }}"

    # - name: unzip the JDK installer file.
    #   become: true
    #   unarchive:
    #     src: "{{  jdk8_installer_path }}"
    #     dest: "/opt"
    #     remote_src: true





    # - name: unzip jdk file.
    #   unarchive:
    #     src: "{{ local_jdk_path }}"
    #     dest: "{{ installation_dir }}"

    # - name: create a symbolic link to the installed directory
    #   file:
    #     src: "{{ installation_dir }}/{{ jdk_dir }}"
    #     dest: "{{ final_dir }}"
    #     state: link

    # - name: add bin directory to path
    #   lineinfile: >
    #     dest=/etc/environment 
    #     state=present 
    #     backrefs=yes
    #     regexp='PATH=(["]*)((?!.*?{{final_dir}}/bin).*?)(["]*)$'
    #     line="PATH=\1\2:{{final_dir}}/bin\3"

    # - name: add an environment variable, 'JAVA_HOME'
    #   lineinfile:
    #     path: /etc/environment
    #     line: "JAVA_HOME={{ final_dir }}"