---
- name: Install required system packages
  become: true
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - lsb-release
    state: latest
    update_cache: true

- name: add Docker GPG apt key
  become: true
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: add Docker Repository
  become: true
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: update apt and install docker-ce, docker-compose, and others
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: add user to docker
  become: true
  user: name="{{ user_id }}" groups=docker append=true

- name: Install LazyDocker and set alias for it
  block:
    - name: Check if lazydocker is installed
      stat:
        path: "{{ user_home_dir }}/.local/bin/lazydocker"
      register: lazydocker_check
      become: false

    - name: Install LazyDocker if not installed
      shell: "curl -s https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"
      when: lazydocker_check.stat.exists == false
      become: false

    - name: Set alias for LazyDocker
      lineinfile:
        dest: ~/.bashrc
        regexp: '^# The followings are aliases defined during Ansible automation'
        line: "alias lzd='layzydocker'"
        state: present
      when: lazydocker_check.stat.exists == false
      become: false