---
vscode_gpg_url: https://packages.microsoft.com/keys/microsoft.asc
vscode_repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main" 