---
- name: install Vim
  become: true
  package: name=vim
  
- name: copy colorschema
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ user_home_dir }}/.vim/colors/"
    mode: '0644'
  with_fileglob:
    - "files/*.vim"

- name: Vim 설정 파일 복사
  ansible.builtin.copy:
    src: files/vimrc
    dest: "{{ user_home_dir }}/.vimrc"
    mode: '0644'

- name: Create alias for vi
  ansible.builtin.lineinfile:
    path: "{{ user_home_dir }}/.bashrc"
    regexp: "^alias vi="
    line: "alias vi='vim'"
    state: present
    insertafter: EOF
