---
- name: install ROS2 package
  hosts: all
  
  vars:
    user_home_dir: "{{ ansible_env.HOME }}"
    ros2_domain_id: 31

  tasks:
    - name: Ensure that the Ubuntu Universe repository is enabled.
      package:
        name:
          - software-properties-common
          - curl
          - gnupg2
          - lsb-release
        state: present
        update_cache: yes
      become: true

    - name: Enable Universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
      become: true

    - name: ROS 2 GPG 키 등록
      ansible.builtin.shell: |
        mkdir -p /etc/apt/keyrings
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | tee /etc/apt/keyrings/ros-archive-keyring.gpg > /dev/null
      args:
        creates: /etc/apt/keyrings/ros-archive-keyring.gpg
      become: true

    - name: ROS 2 저장소 라인 추가
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main"
        state: present
        filename: ros2
        update_cache: yes
      become: true

    - name: Install ROS 2 Humble packages
      package:
        name:
          - ros-humble-desktop
          - ros-dev-tools
          - ros-humble-rmw-cyclonedds-cpp
        state: present
      become: true

    - name: Configure ROS2 settings
      block:
        - name: Remove the previous ROS2 configuration
          blockinfile:
            path: "{{ user_home_dir }}/.bashrc"
            marker: "# ROS2: {mark}"
            state: absent
        - name: Configure ROS2 in bashrc
          blockinfile:
            path: "{{ user_home_dir }}/.bashrc"
            prepend_newline: yes
            append_newline: yes
            marker: "# ROS2: {mark}"
            block: |
              source /opt/ros/humble/setup.bash
              source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

              alias cc='colcon'
              
              export RCUTILS_COLORIZED_OUTPUT=1
              export ROS2_DOMAIN_ID={{ ros2_domain_id }}
              export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
              export LD_LIBRARY_PATH=/opt/ros/humble/lib:$LD_LIBRARY_PATH
      become: false

    - name: Install ROS2 Python dependencies
      package:
        name:
          - python3-colcon-common-extensions
          - python3-rosdep
          - python3-argcomplete
        state: present
      become: true

    - name: Install turtlesim
      package: 
        name: ros-humble-turtlesim 
        state: present
      become: true

    - name: Check turtlesim is installed
      shell: |
        source /opt/ros/humble/setup.bash
        ros2 pkg executables turtlesim
      args:
        executable: /bin/bash
      ignore_errors: yes
      become: false

    - name: Install rqt
      package:
        name: 
          - ros-humble-rqt
          - ros-humble-rqt-common-plugins
          - ros-humble-rqt-graph
          - ros-humble-rqt-plot
        state: present
      become: true

    - name: Initialize rosdep
      shell: |
        rosdep init
        rosdep update
      args:
        executable: /bin/bash
      become: true

    - name: Install rosbridge-suite
      package:
        name: ros-humble-rosbridge-suite
        state: present
      become: true