---
- name: Apache Kafka Installation
  hosts: kafka-nodes
  become: true
  vars:
    - kafka_url: https://downloads.apache.org/kafka/3.6.1/kafka_2.13-3.6.1.tgz
    - installation_dir: /opt
    - kafka_dir_name: kafka_2.13-3.6.1
    - kafka_home_dir: "{{ installation_dir }}/kafka"
    - heap_size: "1G"

  tasks:
    - name: create a group for Kafka
      group: name=kafka state=present

    - name: create a user for Kafka
      user: name=kafka state=present group=kafka create_home=false

    - name: download the kafka gzip file and unarchive it.
      unarchive:
        src: "{{ kafka_url }}"
        dest: "{{ installation_dir }}"
        mode: 0755
        remote_src: true

    - name: chown the installed directory
      file:
        path: "{{ installation_dir }}/{{ kafka_dir_name }}"
        owner: kafka
        group: kafka
        recurse: true

    - name: create a symbolic link to the installed directory
      file:
        src: "{{ installation_dir }}/{{ kafka_dir_name }}"
        dest: "{{ kafka_home_dir }}"
        state: link

    - name: update the Java heap size for Kafka
      become_user: kafka
      replace:
        path: "{{ kafka_home_dir }}/bin/kafka-server-start.sh"
        regexp: 'export KAFKA_HEAP_OPTS=(".+")'
        replace: 'export KAFKA_HEAP_OPTS="-Xmx{{ heap_size }} -Xms{{ heap_size }}"'
