---
- name: Install ubuntu-desktop and gnome
  package:
    name:
      - ubuntu-desktop
  become: true

- name: Set desktop interface settings
  shell: |
    gsettings set org.gnome.desktop.interface font-name "Nanum Gothic 11"
    gsettings set org.gnome.desktop.interface document-font-name "Nanum Gothic 11"
    gsettings set org.gnome.desktop.interface monospace-font-name "D2Coding 12"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
    gsettings set org.gnome.desktop.interface font-hinting "slight"
    gsettings set org.gnome.desktop.wm.preferences titlebar-font "Nanum Gothic Bold 11"

    gsettings set org.gnome.shell.extensions.dash-to-dock click-action "'minimize'"
    gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size "48"
    gsettings set org.gnome.shell.extensions.dash-to-dock dock-position "'LEFT'"
    gsettings set org.gnome.shell.extensions.dash-to-dock show-trash "false"

    gsettings set org.gnome.shell favorite-apps "['google-chrome.desktop', 'code.desktop', 'com.gexperts.Tilix.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'snap-store_ubuntu-software.desktop', 'gnome-control-center.desktop']"
  args:
    executable: /bin/bash
  become: false

- name: Install Nautilus-share (Nautilus에서 Samba를 이용한 공유를 위한 플러그인)
  package: name=nautilus-share
  become: true