---
user_id: "{{ ansible_user_id }}"
user_home_dir: "{{ ansible_env.HOME }}"

set_default_terminal: true

tilix_conf_top: "/com/gexperts/Tilix"
profile_key: "{{ tilix_conf_top }}/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d"
tilix_confs:
  - { key: "{{ tilix_conf_top }}/terminal-title-style", value: "'none'" }
  - { key: "{{ tilix_conf_top }}/enable-wide-handle", value: "true" }

  - { key: "{{ profile_key }}/visible-name", value: "'Default'" }
  
  - { key: "{{ profile_key }}/font", value: "'D2Coding 12'" }
  - { key: "{{ profile_key }}/use-system-font", value: "false" }

  - { key: "{{ profile_key }}/default-size-columns", value: "130" }
  - { key: "{{ profile_key }}/default-size-rows", value: "35" }

  - { key: "{{ profile_key }}/terminal-bell", value: "'none'" }

  - { key: "{{ profile_key }}/login-shell", value: "true" }

  - key: "{{ profile_key }}/palette"
    value: "['#000000', '#CC0000', '#4D9A05', '#C3A000', '#3464A3', '#754F7B', '#05979A', '#D3D6CF', '#545652', '#EF2828', '#89E234', '#FBE84F', '#729ECF', '#AC7EA8', '#34E2E2', '#EDEDEB']"
  - { key: "{{ profile_key }}/foreground-color", value: "'#EFEFEF'" }
  - { key: "{{ profile_key }}/background-color", value: "'#303030'" }
  - { key: "{{ profile_key }}/use-theme-colors", value: "false" }
  - { key: "{{ profile_key }}/badge-color", value: "'#AC7EA8'" }
  - { key: "{{ profile_key }}/badge-color-set", value: "true" }
  - { key: "{{ profile_key }}/bold-color-set", value: "true" }
  - { key: "{{ profile_key }}/cursor-colors-set", value: "false" }
  - { key: "{{ profile_key }}/highlight-colors-set", value: "false" }
