---
- name: Install Gradle 8.9 directly
  hosts: all
  become: true

  vars:
    gradle_version: "8.9"
    gradle_home: "/opt/gradle"
    gradle_archive: "gradle-{{ gradle_version }}-bin.zip"
    gradle_url: "https://services.gradle.org/distributions/{{ gradle_archive }}"
    gradle_dir: "{{ gradle_home }}/gradle-{{ gradle_version }}"

  tasks:
    - name: Install required packages
      package:
        name:
          - wget
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Create Gradle directory
      file:
        path: "{{ gradle_home }}"
        state: directory
        mode: '0755'

    - name: Check if Gradle is already installed
      stat:
        path: "{{ gradle_dir }}"
      register: gradle_installed

    - name: Download Gradle archive
      get_url:
        url: "{{ gradle_url }}"
        dest: "/tmp/{{ gradle_archive }}"
        mode: '0644'
      when: not gradle_installed.stat.exists

    - name: Extract Gradle archive
      unarchive:
        src: "/tmp/{{ gradle_archive }}"
        dest: "{{ gradle_home }}"
        remote_src: yes
        creates: "{{ gradle_dir }}"
      when: not gradle_installed.stat.exists

    - name: Create symbolic link for Gradle
      file:
        src: "{{ gradle_dir }}"
        dest: "{{ gradle_home }}/gradle"
        state: link
        force: yes

    - name: Check if PATH contains Gradle
      shell: |
        grep -q "GRADLE_HOME/bin" /etc/environment || echo "not_found"
      register: gradle_in_path

    - name: Add GRADLE_HOME to /etc/environment
      lineinfile:
        path: /etc/environment
        regexp: '^GRADLE_HOME='
        line: 'GRADLE_HOME={{ gradle_home }}/gradle'
        state: present

    - name: Add Gradle bin to PATH in /etc/environment
      replace:
        path: /etc/environment
        regexp: '^PATH="([^"]*)"'
        replace: 'PATH="\1:$GRADLE_HOME/bin"'
      when: "'not_found' in gradle_in_path.stdout"

    - name: Add Gradle to PATH in /etc/profile.d
      copy:
        content: |
          export GRADLE_HOME={{ gradle_home }}/gradle
          export PATH=$PATH:$GRADLE_HOME/bin
        dest: /etc/profile.d/gradle.sh
        mode: '0644'

    - name: Set Gradle alternatives
      alternatives:
        name: gradle
        path: "{{ gradle_home }}/gradle/bin/gradle"
        link: /usr/bin/gradle
        priority: 100

    - name: Clean up downloaded archive
      file:
        path: "/tmp/{{ gradle_archive }}"
        state: absent
      when: not gradle_installed.stat.exists

    - name: Verify Gradle installation
      shell: |
        source /etc/profile.d/gradle.sh
        gradle --version | head -1
      args:
        executable: /bin/bash
      register: gradle_version_output
      ignore_errors: yes

    - name: Display installation result
      debug:
        msg: |
          Gradle installation completed!
          Installed version: {{ gradle_version_output.stdout | default('Installation completed, please restart shell or run: source /etc/profile.d/gradle.sh') }}
          Gradle home: {{ gradle_home }}/gradle
          Binary location: {{ gradle_home }}/gradle/bin/gradle 