---
- name: Install Eclipse Temurin JDK 21
  hosts: all
  become: true

  vars:
    jdk_version: "21"
    jdk_home: "/opt/temurin"
    jdk_dir: "{{ jdk_home }}/jdk-{{ jdk_version }}"
    temurin_repo_url: "https://packages.adoptium.net/artifactory/deb"
    temurin_gpg_url: "https://packages.adoptium.net/artifactory/api/gpg/key/public"

  tasks:
    - name: Install required packages
      package:
        name:
          - wget
          - curl
          - gnupg2
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Eclipse Temurin GPG key
      get_url:
        url: "{{ temurin_gpg_url }}"
        dest: /etc/apt/keyrings/temurin.asc
        mode: '0644'

    - name: Add Eclipse Temurin repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/temurin.asc] {{ temurin_repo_url }} {{ ansible_distribution_release }} main"
        state: present
        filename: temurin
        update_cache: yes

    - name: Install Eclipse Temurin JDK 21
      package:
        name: "temurin-{{ jdk_version }}-jdk"
        state: present
        update_cache: yes

    - name: Create JDK directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ jdk_home }}"
        - "{{ jdk_dir }}"

    - name: Create symbolic link for JDK
      file:
        src: "/usr/lib/jvm/temurin-{{ jdk_version }}-jdk-amd64"
        dest: "{{ jdk_dir }}"
        state: link
        force: yes

    - name: Add JAVA_HOME to /etc/profile.d
      copy:
        content: |
          export JAVA_HOME={{ jdk_dir }}
          export PATH=$JAVA_HOME/bin:$PATH
        dest: /etc/profile.d/temurin-jdk.sh
        mode: '0644'

    - name: Add JAVA_HOME to /etc/environment
      lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME={{ jdk_dir }}'
        state: present

    # - name: Add Java bin to PATH in /etc/environment
    #   lineinfile:
    #     path: /etc/environment
    #     regexp: '^PATH='
    #     line: 'PATH=$JAVA_HOME/bin:$PATH'
    #     state: present
    #     insertafter: '^JAVA_HOME='

    - name: Set Java alternatives
      alternatives:
        name: java
        path: "{{ jdk_dir }}/bin/java"
        link: /usr/bin/java
        priority: 100

    - name: Set javac alternatives
      alternatives:
        name: javac
        path: "{{ jdk_dir }}/bin/javac"
        link: /usr/bin/javac
        priority: 100

    # - name: Verify Java installation
    #   shell: |
    #     source /etc/profile.d/temurin-jdk.sh
    #     java -version
    #   register: java_version_output
    #   ignore_errors: yes

    # - name: Verify Java compiler installation
    #   shell: |
    #     source /etc/profile.d/temurin-jdk.sh
    #     javac -version
    #   register: javac_version_output
    #   ignore_errors: yes

    - name: Display installation result
      debug:
        msg: |
          Eclipse Temurin JDK {{ jdk_version }} installation completed!
          Java version: {{ java_version_output.stdout | default('Installation completed, please restart shell or run: source /etc/profile.d/temurin-jdk.sh') }}
          Java compiler version: {{ javac_version_output.stdout | default('Not available') }}
          JAVA_HOME: {{ jdk_dir }}
          Java binary: {{ jdk_dir }}/bin/java 