---
- name: xrdp 및 dependent 모듈 설치
  become: true
  package:
    name:
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xrdp
    state: latest

- name: xrdp 포트 번호 설정 (WSL2인 경우)
  become: true
  lineinfile:
    dest: /etc/xrdp/xrdp.ini
    regexp: "^port=3389"
    line: "port=3390"
    state: present
  when: ansible_virtualization_type == 'wsl' and xrdp_port == 3389

- name: xrdp 포트 번호 설정 (3389가 아닌 경우)
  become: true
  lineinfile:
    dest: /etc/xrdp/xrdp.ini
    regexp: "^port=3389"
    line: "port={{ xrdp_port }}"
    state: present
  when: xrdp_port != 3389

- name: xrdp에 SSL 인증서 접근 권한 추가
  become: true
  user: name=xrdp group=ssl-cert
  notify: restart xrdp

- name: xrdp 설정 변경 (접속시 검은 화면만 보이는 문제 해결)
  become: true
  lineinfile:
    dest: /etc/xrdp/startwm.sh
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^unset DBUS_SESS"
      line: "unset DBUS_SESSION_BUS_ADDRESS"
    - regexp: "^unset XDG_RUNTIME"
      line: "unset XDG_RUNTIME_DIR"
  notify: restart xrdp

- name: Login 과정에서 password 입력 후 멈추는 문제 해결 1/2
  become: true
  command: systemctl set-default graphical
- name: Login 과정에서 password 입력 후 멈추는 문제 해결 2/2
  become: true
  command: systemctl isolate graphical

- name: xrdp 접속 중 Password를 지속적으로 물어보는 현상 해결 (1/2)
  become: true
  copy:
    dest: /etc/polkit-1/localauthority/50-local.d/color.pkla
    content: |
      [Allow colord for all users]
      Identity=unix-user:*
      Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
      ResultAny=yes
      ResultInactive=yes
      ResultActive=yes
    mode: 0755
  notify: restart xrdp

- name: xrdp 접속 중 Password를 지속적으로 물어보는 현상 해결 (2/2)
  become: true
  copy:
    dest: /etc/polkit-1/localauthority/45-allow-colord.pkla
    content: |
      [Allow Colord all Users]
      Identity=unix-user:*
      Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
      ResultAny=no
      ResultInactive=no
      ResultActive=yes

      [Allow Package Management all Users]
      Identity=unix-user:*
      Action=org.debian.apt.*;io.snapcraft.*;org.freedesktop.packagekit.*;com.ubuntu.update-notifier.*
      ResultAny=no
      ResultInactive=no
      ResultActive=yes
    mode: 0755
  notify: restart xrdp

- name: xsessionrc 파일 생성
  copy:
    dest: "{{ user_home_dir }}/.xsessionrc"
    content: |
      export GNOME_SHELL_SESSION_MODE=ubuntu
      export XDG_CURRENT_DESKTOP=ubuntu:GNOME
      export XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
      export XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
      export WAYLAND_DISPLAY=
    mode: 0644
  notify: restart xrdp
