---
- name: Add a database for PostgreSQL
  hosts: all

  vars:
    postgres_db: ""
    postgres_user: ""

  tasks:
    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
        state: present
      become: true
      become_user: postgres
      when: postgres_user != "" and postgres_db != ""

    - name: Grant privileges to user on database
      postgresql_privs:
        db: "{{ postgres_db }}"
        roles: "{{ postgres_user }}"
        type: "database"
        privs: "ALL"
      become: true
      become_user: postgres
      when: postgres_user != "" and postgres_db != ""