---
- name: PostgreSQL Installation
  hosts: all

  vars:
    postgres_user: mdt
    postgres_db: mdt
    postgres_password: urc2004

  tasks:
    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        state: present
      become: true
      become_user: postgres

    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
        state: present
      become: true
      become_user: postgres

    - name: Grant privileges to user on database
      postgresql_privs:
        db: "{{ postgres_db }}"
        roles: "{{ postgres_user }}"
        type: "database"
        privs: "ALL"
      become: true
      become_user: postgres