---
galaxy_info:
  author: Ansible User
  description: Create PostgreSQL user with configurable options
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - postgresql
    - postgres
    - user
    - database

dependencies: [] 