---
# Yarn default variables

# Yarn 설치 관련 설정
yarn_install_method: "npm"  # npm, corepack, 또는 repository
yarn_version: "latest"      # 특정 버전 또는 latest
yarn_install_global: true   # 전역 설치 여부

# Node.js 설정 (nodejs role에서 사용)
nodejs_version: "22.x"
nodejs_install_global_packages: []

# Yarn 설정
yarn_config_registry: "https://registry.yarnpkg.com"  # 기본 레지스트리
yarn_config_cache_folder: "~/.cache/yarn"            # 캐시 폴더
yarn_config_global_folder: "~/.yarn/global"          # 전역 패키지 폴더

# 보안 설정
yarn_network_timeout: 100000  # 네트워크 타임아웃 (밀리초)
yarn_network_concurrency: 8   # 동시 네트워크 연결 수

# 성능 설정
yarn_enable_telemetry: false  # 텔레메트리 비활성화
yarn_enable_scripts: true     # 스크립트 실행 허용 