---
- name: font config 설치
  become: true
  apt: name=fontconfig update_cache=true

- name: 폰트 디렉토리 생성
  become: true
  file: path="{{ d2conding_dir }}" state=directory

- name: D2Coding 1.3.2 다운로드 및 압축 풀기
  become: true
  unarchive:
    src: "{{ d2coding_font_url }}"
    dest: "{{ d2conding_dir }}"
    creates: "{{ d2conding_dir }}/D2Coding"
    remote_src: true
  register: unarchived
    
- name: 폰트 캐시 갱신
  command: fc-cache -f -v
  when: unarchived.changed