---
- name: "Read dconf key: {{ item.key }}"
  command: dconf read {{ item.key }}
  register: r_dconf_current_value
  changed_when: no

- name: "Write dconf key: {{ item.key }}"
  become: true
  command: dbus-launch dconf write {{ item.key }} "{{ item.value }}"
  when: r_dconf_current_value.stdout != item.value