---
- hosts: 127.0.0.1
  connection: local

  vars:
    user_id: "{{ ansible_user_id }}"
    user_home_dir: "{{ ansible_env.HOME }}"

  pre_tasks:
    - name: update and upgrade apt
      become: true
      apt: upgrade=yes update_cache=yes cache_valid_time=3600

  roles:
    - role: vim
    - role: font_d2coding
    - role: generate_ssh_key

  tasks:
    - name: Desktop 사용자에게 sudo 권한 부여
      include_tasks: tasks/task_allow_sudoer.yml

    - name: Bash 설정 파일 복사
      include_tasks: tasks/task_bashrc.yml

    - name: install some terminal applications
      include_tasks: tasks/task_tools.yml
