---
- hosts: 127.0.0.1
  connection: local

  vars:
    user_id: "{{ ansible_user_id }}"
    user_home_dir: "{{ ansible_env.HOME }}"

  # pre_tasks:
  #   - name: install python3-pip
  #     become: true
  #     package: name=python3-pip

  #   - name: install ansible-toolbox
  #     become: true
  #     pip: name=git+https://github.com/larsks/ansible-toolbox

  tasks:
    - name: Desktop 사용자에게 sudo 권한 부여
      include_tasks: tasks/task_allow_sudoer.yml

    - name: update and upgrade apt
      become: true
      apt: upgrade=yes update_cache=yes cache_valid_time=3600

    - name: Bash 설정 파일 복사
      include_tasks: tasks/task_bashrc.yml

    - name: install some terminal applications
      include_tasks: tasks/task_tools.yml

    - include_role: name=font_d2coding
      become: true

    - include_role: name=vim
      vars:
        user_id: "{{ user_home_dir  }}"

    - include_role: name=generate_ssh_key
      vars:
        user_id: "{{ user_home_dir  }}"
