---
- hosts: 127.0.0.1
  connection: local

  vars:
    user_id: "{{ ansible_user_id }}"
    user_home_dir: "{{ ansible_env.HOME }}"
    
  roles:
    - role: tmux
    - role: python3
    # - role: jdk8_oracle
    - role: vscode
      when: ansible_virtualization_type != 'wsl'
    - role: docker-engine
    - role: Comcast.sdkman
      sdkman_user: "{{ user_id }}"
      sdkman_group: "{{ user_id }}"
      sdkman_install_packages:
        - { candidate: java, version: 21.0.2-tem }
        - { candidate: gradle, version: 7.6.4 }
      sdkman_auto_answer: true
      sdkman_update: true

  tasks:
    - name: install python3-pip
      become: true
      package: name=python3-pip
    - name: install ansible-toolbox
      become: true
      pip: name=git+https://github.com/larsks/ansible-toolbox