---
- name: Dconf 관련 모듈 설치
  hosts: all
  become: true
  tasks:
    - name: 주요 모듈들 설치
      become: true
      package:
        name:
          - dconf-cli
          - dconf-editor
          - gnome-tweaks
          # - dbus-x11
    - name: dconf 관련 모듈 설치
      become: true
      pip: name=psutil


- name: GUI Application Installation
  hosts: all
  become: true
  roles:
    - role: gnome-terminal
    - role: tilix
    - role: google-chrome
    - role: ubuntu_desktop
    - role: xrdp