---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars_files:
    - global_vars.yml
  vars:
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb https://download.docker.com/linux/ubuntu jammy stable"
    gradle_version: 7.6.3

  pre_tasks:
  - name: update and upgrade apt
    become: true
    apt: upgrade=yes update_cache=yes cache_valid_time=3600

  tasks:
  - name: Desktop 사용자에게 sudo 권한 부여
    include_tasks: tasks/task_allow_sudoer.yml

  - name: Bash 설정 파일 복사
    include_tasks: tasks/task_bashrc.yml

  - name: install some terminal applications
    include_tasks: tasks/task_tools.yml

  - name: D2Coding 폰트 설치 여부 확인
    stat: path=/usr/share/fonts/d2coding
    register: d2coding_installed
  - name: D2Coding 폰트 설치
    include_tasks: tasks/task_d2coding.yml
    when: not d2coding_installed.stat.exists

  - name: install Vim
    include_tasks: tasks/task_vim.yml

  - name: install TMux
    include_tasks: tasks/task_tmux.yml

  - name: VSCode 설치 여부 확인
    stat: path=/usr/bin/code
    register: vscode_installed
  - name: install VSCode
    include_tasks: tasks/task_vscode.yml
    when: not vscode_installed.stat.exists

  - name: Miniconda3 설치 여부 확인
    stat: path=~/miniconda3
    register: miniconda_installed
  - name: install Miniconda3
    include_tasks: tasks/task_miniconda3.yml
    when: not miniconda_installed.stat.exists

  - name: install SDKMan
    become: false
    shell: 'curl -s "https://get.sdkman.io" | bash'
    args:
      executable: /bin/bash
      creates: ~/.sdkman

  - name: Chrome 설치 여부 확인
    stat: path=/usr/bin/google-chrome
    register: chrome_installed
  - name: install Google Chrome
    include_tasks: tasks/task_chrome.yml
    when: not chrome_installed.stat.exists

  - name: Docker 설치 여부 확인
    stat: path=/usr/bin/docker
    register: docker_installed
  - name: install Docker
    include_tasks: tasks/task_docker.yml
    when: not docker_installed.stat.exists

  - name: ensure .ssh directory
    file: path="~/.ssh" state=directory
  - name: create SSH key
    command: ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -N '' -q
    args:
      creates: ~/.ssh/id_rsa
